FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="skh951225.com"

COPY ./default.conf.tpl /etc/nginx/default.conf.tpl
COPY ./dist /var/www/html
COPY ./uwsgi_params /etc/nginx/uwsgi_params
COPY ./proxy_params /etc/nginx/proxy_params
COPY ./run.sh /run.sh

ENV LISTEN_PORT=8000
ENV APP_HOST=app
ENV APP_PORT=9000
ENV WS_PORT=8000

USER root

RUN mkdir -p /vol/static && \
    chmod 755 /vol/static && \
    touch /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /var/log/nginx/ && \
    chmod +x /run.sh

VOLUME /vol/static

USER nginx

CMD ["/run.sh"]