# Generated by Django 3.2.20 on 2023-07-27 10:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='music_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
