# Generated by Django 3.2.20 on 2023-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_room_music_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
