# Generated by Django 3.2.20 on 2023-07-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_room_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='id',
            new_name='music_id',
        ),
    ]
