# Generated by Django 3.2.20 on 2023-08-03 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='music_length',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
