# Generated by Django 3.2.20 on 2023-08-03 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_room_music_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='music_length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
