# Generated by Django 3.2.20 on 2023-08-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230806_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='singers',
            field=models.ManyToManyField(blank=True, null=True, to='core.Singer'),
        ),
        migrations.AlterField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.Tag'),
        ),
    ]
