# Generated by Django 3.2.20 on 2023-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230806_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AlterField(
            model_name='music',
            name='singers',
            field=models.ManyToManyField(blank=True, to='core.Singer'),
        ),
        migrations.AlterField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
