# Generated by Django 3.2.20 on 2023-07-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_id_music_music_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='music_id',
            new_name='id',
        ),
    ]
