# Generated by Django 3.2.20 on 2023-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230730_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
