# Generated by Django 3.2.20 on 2023-08-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_room_music_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='running_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(null=True, to='core.Tag'),
        ),
    ]
