# Generated by Django 3.2.20 on 2023-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230806_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='music_tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
